BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Stay] ADD [cleaningRequested] BIT NOT NULL CONSTRAINT [Stay_cleaningRequested_df] DEFAULT 0,
[renewalCount] INT NOT NULL CONSTRAINT [Stay_renewalCount_df] DEFAULT 0,
[renewedAt] DATETIME2;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
