BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Rate] ADD [pernocta] BIT NOT NULL CONSTRAINT [Rate_pernocta_df] DEFAULT 0,
[special] BIT NOT NULL CONSTRAINT [Rate_special_df] DEFAULT 0;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
